//! Context fragments injected into model input.

mod approved_command_prefix_saved;
mod apps_instructions;
mod available_plugins_instructions;
mod available_skills_instructions;
mod collaboration_mode_instructions;
mod completion_checkpoint;
mod completion_review_repair;
mod contextual_user_message;
mod current_time_reminder;
mod environment_context;
mod guardian_followup_review_reminder;
mod hook_additional_context;
mod image_generation_instructions;
mod inter_agent_completion_message;
mod internal_model_context;
mod model_switch_instructions;
mod multi_agent_mode_instructions;
mod network_rule_saved;
mod personality_spec_instructions;
mod plugin_instructions;
mod prompt_provenance;
mod recommended_plugins_instructions;
mod subagent_notification;
mod task_capsule;
mod task_model_guidance;
mod turn_aborted;
mod user_instructions;
mod user_shell_command;
pub(crate) mod world_state;

pub(crate) use approved_command_prefix_saved::ApprovedCommandPrefixSaved;
pub(crate) use apps_instructions::AppsInstructions;
pub(crate) use apps_instructions::AppsInstructionsUnavailable;
pub(crate) use available_plugins_instructions::AvailablePluginsInstructions;
pub(crate) use available_plugins_instructions::PluginsInstructionsUnavailable;
pub use available_skills_instructions::AvailableSkillsInstructions;
pub(crate) use available_skills_instructions::SKILLS_USAGE_INSTRUCTIONS_OPEN_TAG;
pub(crate) use available_skills_instructions::SkillsUsageInstructions;
pub(crate) use codex_context_fragments::AdditionalContextDeveloperFragment;
pub(crate) use codex_context_fragments::AdditionalContextUserFragment;
pub use codex_context_fragments::ContextualUserFragment;
pub(crate) use codex_context_fragments::FragmentRegistration;
pub(crate) use codex_context_fragments::FragmentRegistrationProxy;
pub(crate) use codex_core_skills::injection::SkillInjection;
pub use codex_prompts::ApprovalPromptContext;
pub use codex_prompts::PermissionsInstructions;
pub(crate) use collaboration_mode_instructions::CollaborationModeInstructions;
pub(crate) use completion_checkpoint::CompletionCheckpointContext;
pub(crate) use completion_review_repair::CompletionReviewRepair;
pub(crate) use contextual_user_message::is_contextual_user_fragment;
pub(crate) use contextual_user_message::is_legacy_compaction_warning_fragment;
pub(crate) use contextual_user_message::is_startup_contextual_user_fragment;
pub(crate) use contextual_user_message::is_task_evidence_context_fragment;
pub(crate) use contextual_user_message::parse_visible_hook_prompt_message;
pub(crate) use current_time_reminder::CurrentTimeReminder;
pub(crate) use guardian_followup_review_reminder::GuardianFollowupReviewReminder;
pub(crate) use hook_additional_context::HookAdditionalContext;
pub use image_generation_instructions::extension_image_generation_output_hint;
pub(crate) use inter_agent_completion_message::InterAgentCompletionMessage;
pub use internal_model_context::InternalContextSource;
pub use internal_model_context::InternalModelContextFragment;
pub use internal_model_context::InvalidInternalContextSource;
pub(crate) use model_switch_instructions::ModelSwitchInstructions;
pub(crate) use multi_agent_mode_instructions::EffectiveMultiAgentMode;
pub(crate) use multi_agent_mode_instructions::MultiAgentModeInstructions;
pub(crate) use multi_agent_mode_instructions::RootOrchestrationInstructions;
pub(crate) use network_rule_saved::NetworkRuleSaved;
pub(crate) use personality_spec_instructions::PersonalitySpecInstructions;
pub(crate) use plugin_instructions::PluginInstructions;
pub(crate) use prompt_provenance::CategorizedPromptFragment;
pub(crate) use prompt_provenance::PromptContextBreakdown;
pub(crate) use prompt_provenance::PromptContextCategory;
pub(crate) use prompt_provenance::PromptContextMeasurement;
pub(crate) use prompt_provenance::PromptProvenanceSidecar;
pub(crate) use recommended_plugins_instructions::RecommendedPluginsInstructions;
pub(crate) use subagent_notification::SubagentNotification;
pub(crate) use task_capsule::TaskCapsuleFragment;
pub(crate) use task_model_guidance::TaskModelGuidance;
pub(crate) use task_model_guidance::base_instructions_own_task_model_guidance;
pub(crate) use turn_aborted::TurnAborted;
pub(crate) use user_instructions::UserInstructions;
pub(crate) use user_shell_command::UserShellCommand;
