// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BugCreateResponse = { id: bigint, displayId: string,
/**
 * Always `pending` when returned; persistence has committed already.
 */
status: string, durableSaveResult: boolean, };
