// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact decoded report text. The server accepts no attachments or turn data.
 */
export type BugCreateParams = { threadId: string, rawText: string, };
