// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PtyTerminalSize } from "./PtyTerminalSize";

/**
 * PTY size in character cells for `command/exec` PTY sessions.
 */
export type CommandExecTerminalSize = PtyTerminalSize;
