// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecOutputStream } from "../ExecOutputStream";

export type CommandExecutionOutputDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string,
/**
 * Origin of this delta; absent only for legacy producers.
 */
stream?: ExecOutputStream,
/**
 * Whether invalid UTF-8 was replaced while decoding this delta.
 */
decodingLossy?: boolean, };
