// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopActivationObligation = { threadId: string, evidenceEpoch: bigint, implementationIdentity: string, activationObligationIdentity: string, requiringPlanStepIds: Array<string>, };
