// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopActivationChallenge = { challengeId: string, threadId: string, evidenceEpoch: bigint, implementationIdentity: string, activationObligationIdentity: string, publisherEvidenceId: string, expectedInstalledExecutablePath: string, expectedInstalledExecutableSha256: string, publishId: string, issuedAt: string, expiresAt: string, };
