// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeterministicContinuationClass = "unchanged_wait" | "artifact_range" | "source_projection" | "agent_event_wait";
