// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeterministicContinuationHostAction = "await_state_change" | "batch_source_bundle" | "reuse_covered_span" | "read_missing_ranges" | "drain_artifact_ranges";
