// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnError } from "./TurnError";

export type ErrorNotification = { error: TurnError,
/**
 * Whether the server will retry automatically. When true, the turn remains
 * active; clients should not initiate a duplicate retry for this notification.
 */
willRetry: boolean, threadId: string, turnId: string, };
