// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { WorkspaceRouting } from "./WorkspaceRouting";

export type GetAccountResponse = { account: Account | null, requiresOpenaiAuth: boolean,
/**
 * Authoritative routing for the signed-in ChatGPT workspace, when available.
 */
workspaceRouting: WorkspaceRouting | null, };
