// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { PathUri } from "../PathUri";
import type { RequestPermissionProfile } from "./RequestPermissionProfile";

export type PermissionsRequestApprovalParams = { threadId: string, turnId: string, itemId: string, environmentId: string | null,
/**
 * Unix timestamp (in milliseconds) when this approval request started.
 */
startedAtMs: number,
/**
 * Legacy native working directory. For foreign selected environments this
 * is a compatibility fallback; `cwd_uri` is authoritative.
 */
cwd: AbsolutePathBuf,
/**
 * URI-preserving working directory for the selected environment.
 */
cwdUri: PathUri, reason: string | null, permissions: RequestPermissionProfile, };
