// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical PTY size payload shared by app-server process APIs.
 */
export type PtyTerminalSize = {
/**
 * Terminal height in character cells.
 */
rows: number,
/**
 * Terminal width in character cells.
 */
cols: number, };
