// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInput } from "./UserInput";

/**
 * A durable follow-up, in queue order. Starting it uses the current thread settings.
 */
export type QueuedSubmission = { id: string, clientUserMessageId: string | null, input: Array<UserInput>, };
