// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type SkillInterface = { displayName?: string | null, shortDescription?: string | null, iconSmall?: AbsolutePathBuf | null, iconLarge?: AbsolutePathBuf | null, brandColor?: string | null, defaultPrompt?: string | null, };
