// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Authoritative typed tool result surfaced as the terminal result of a turn.
 * `canonical_message`, when present, is owner-authored and may be copied
 * unchanged into legacy last-message consumers. `value` is never rendered into
 * synthetic assistant prose by the host.
 */
export type SurfacedToolResult = { adapter: string, value: JsonValue, canonicalMessage?: string, };
