// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable classification for recoverable thread request failures.
 */
export type ThreadErrorReason = "notFound" | "notLoaded" | "notMaterialized" | "ephemeralTurnsUnavailable";
