// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadQueueReorderParams = { threadId: string,
/**
 * Listed entries move to the front; omitted entries retain their relative order.
 */
queuedSubmissionIds: Array<string>, };
