// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type ThreadSearchResult = { thread: Thread,
/**
 * The first matching excerpt from persisted rollout content.
 */
snippet: string, };
