// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestUserInputDisposition } from "../RequestUserInputDisposition";
import type { ToolRequestUserInputAnswer } from "./ToolRequestUserInputAnswer";

/**
 * EXPERIMENTAL. Response payload mapping question ids to answers.
 */
export type ToolRequestUserInputResponse = { answers: { [key in string]?: ToolRequestUserInputAnswer }, interrupted: boolean,
/**
 * Absent for legacy clients. Timeout, skip and transport failure never imply approval.
 */
disposition?: RequestUserInputDisposition, };
