// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingToolCallIdentity } from "./TurnTimingToolCallIdentity";

/**
 * Reconciliation summary for all accepted tool executions in a turn.
 *
 * `complete` is true for a turn with no accepted calls. Otherwise it requires
 * every accepted execution to have a timing record, terminal outcome, and
 * exactly-once persisted projection, with no orphan or duplicate lifecycle
 * records and no ledger overflow.
 */
export type TurnTimingToolClosure = { acceptedCount: number, timingPairedCount: number, terminalCount: number, persistedCount: number, duplicateCallIdCount: number, duplicateAcceptanceCount: number, duplicateTimingCount: number, duplicatePersistenceCount: number, orphanTimingCount: number, orphanPersistenceCount: number, overflowCount: number, unresolvedCalls?: Array<TurnTimingToolCallIdentity>, orphanCalls?: Array<TurnTimingToolCallIdentity>, complete: boolean, };
