// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingCounters } from "./TurnTimingCounters";
import type { TurnTimingDeterministicContinuationReceipt } from "./TurnTimingDeterministicContinuationReceipt";
import type { TurnTimingDiagnosticTokenAggregate } from "./TurnTimingDiagnosticTokenAggregate";
import type { TurnTimingExclusive } from "./TurnTimingExclusive";
import type { TurnTimingLocal } from "./TurnTimingLocal";
import type { TurnTimingMilestones } from "./TurnTimingMilestones";
import type { TurnTimingModelRequest } from "./TurnTimingModelRequest";
import type { TurnTimingPreEditConvergence } from "./TurnTimingPreEditConvergence";
import type { TurnTimingPreFirstModelOutput } from "./TurnTimingPreFirstModelOutput";
import type { TurnTimingTerminalization } from "./TurnTimingTerminalization";
import type { TurnTimingUnions } from "./TurnTimingUnions";

/**
 * Immutable wall-clock profile captured at the core terminal boundary.
 *
 * `exclusive` is the canonical elapsed-time partition. Values in `unions`
 * and `local` may overlap and must not be added to that partition.
 */
export type TurnTiming = { schemaVersion: number, profileValid: boolean, classificationComplete: boolean, startedAtUnixMs: number | null, completedAtUnixMs: number | null, inclusiveDurationNs: bigint, inclusiveDurationMs: bigint,
/**
 * Inclusive duration minus only the interactive-only wait partition.
 */
machineDurationNs: bigint, machineDurationMs: bigint, exclusive: TurnTimingExclusive, unions: TurnTimingUnions, local: TurnTimingLocal, milestones: TurnTimingMilestones, counters: TurnTimingCounters,
/**
 * Additive terminalization phase timings. Older records deserialize to zeroes; the
 * terminalization receipt remains authoritative for phases that occur after live dispatch.
 */
terminalization: TurnTimingTerminalization,
/**
 * Per-sampling-request milestones, ordered by request. Times are offsets
 * from turn start and are diagnostic only; they are not additive buckets.
 */
modelRequests?: Array<TurnTimingModelRequest>,
/**
 * Provider usage observed on generations where neither relevant
 * structured state nor the next-correct-action changed. This is a
 * diagnostic and is never treated as measured avoidable savings.
 */
observationalNonprogressTokens: TurnTimingDiagnosticTokenAggregate,
/**
 * Bounded, aggregated host-managed continuation receipts. Resource
 * identities are hashes; raw paths and payloads are never included.
 */
deterministicContinuationReceipts?: Array<TurnTimingDeterministicContinuationReceipt>, deterministicContinuationReceiptOverflow: number, preFirstModelOutput?: TurnTimingPreFirstModelOutput,
/**
 * Pre-edit convergence milestones and bounded aggregate counters. Interval
 * durations and count deltas are derived from these snapshots by analysis.
 */
preEditConvergence?: TurnTimingPreEditConvergence, };
