// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfacedToolResult } from "./SurfacedToolResult";
import type { Turn } from "./Turn";
import type { TurnTiming } from "./TurnTiming";

export type TurnCompletedNotification = { threadId: string, turn: Turn, timing?: TurnTiming, surfacedResult?: SurfacedToolResult, };
