// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingTokenCategoryBasis } from "./TurnTimingTokenCategoryBasis";

export type TurnTimingRequestTokenCategories = { accountingBasis: TurnTimingTokenCategoryBasis, baseInstructions: bigint, toolSchemas: bigint, conversationHistory: bigint, currentInput: bigint, repositoryContext: bigint, skills: bigint, otherInjectedContext: bigint,
/**
 * Sum of the mutually exclusive category estimates above.
 */
logicalTotal: bigint,
/**
 * One-pass local estimate over the complete serialized logical prompt.
 */
localInputEstimate: bigint,
/**
 * `local_input_estimate - logical_total`. This exposes estimator and JSON
 * envelope effects instead of silently assigning them to a category.
 */
localReconciliationResidual: bigint,
/**
 * Provider-reported full input tokens, when usage was returned.
 */
providerInputTokens?: number | null,
/**
 * `provider_input_tokens - logical_total`, when provider usage exists.
 */
providerReconciliationResidual?: number | null,
/**
 * Overlapping diagnostic: logical tokens in categories whose exact hash
 * matched the preceding request. This is not added to `logical_total`.
 */
repeatedUnchangedContext: bigint, };
