// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingReadinessReopenReasonCounts } from "./TurnTimingReadinessReopenReasonCounts";

export type TurnTimingPreEditConvergence = { acceptedToOwnerResolvedMs?: number | null, ownerResolvedMs?: number | null, ownerResolvedGenerationCount?: number, ownerResolvedToolCallCount?: number, ownerResolvedToBundleReadyMs?: number | null, implementationReadyMs?: number | null, implementationReadyGenerationCount?: number, implementationReadyToolCallCount?: number, firstAcceptedMutationMs?: number | null, firstAcceptedMutationGenerationCount?: number, firstAcceptedMutationToolCallCount?: number, bundleReadyToFirstAcceptedMutationMs?: number | null, mutationBeforeReady: boolean, firstSuccessfulMutationMs?: number | null, firstSuccessfulMutationGenerationCount?: number, firstSuccessfulMutationToolCallCount?: number, materialEvidenceOperations: number, broadDiscoveryAfterReady: number, readinessReopenCount: number, reopenReasonCounts: TurnTimingReadinessReopenReasonCounts, };
