// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingRequestTokenCategories = { baseInstructions: bigint, toolSchemas: bigint, conversationHistory: bigint, currentInput: bigint, repositoryContext: bigint, skills: bigint, otherInjectedContext: bigint, logicalTotal: bigint,
/**
 * Tokens in categories whose exact hash matched the prior model request.
 */
repeatedUnchangedContext: bigint, };
