// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalizationDeliveryState } from "./TerminalizationDeliveryState";
import type { TerminalizationRecoveryState } from "./TerminalizationRecoveryState";
import type { TurnTimingTerminalization } from "./TurnTimingTerminalization";

export type TurnTerminalizationReceipt = { terminalIdentity: string, terminalization: TurnTimingTerminalization, deliveryState: TerminalizationDeliveryState, activeTurnDetached: boolean, terminalInteractionReleased: boolean, recoveryState: TerminalizationRecoveryState, deadlineExhaustedPhase?: string, };
