// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingUnions = { modelActiveUnionNs: bigint, modelActiveUnionMs: bigint, modelRequestWaitUnionNs: bigint, modelStreamWaitUnionNs: bigint, modelStreamProcessingUnionNs: bigint, toolActiveUnionNs: bigint, toolActiveUnionMs: bigint, interactiveWaitUnionNs: bigint, };
