// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingTerminalization = { finalMutationToSealNs: bigint, validationProcessNs: bigint, validationAggregateNs: bigint, completionGateNs: bigint, reviewPreflightNs: bigint, reviewNs: bigint, checkpointTokens: bigint, validationLaunchCount: number, proofReuseCount: number, conservativeRerunCount: number, validationAggregateCount: number, terminalMemoHitCount: number, diffReuseCount: number, diffRefreshCount: number, reviewerInfrastructureMemoHitCount: number, reviewsPreventedByCorrectnessCount: number, preparationNs: bigint, hooksQuiescenceNs: bigint, fenceNs: bigint, freshnessNs: bigint, gateNs: bigint, durableCommitNs: bigint, deliveryAttemptNs: bigint, interactionReleaseNs: bigint, postCleanupNs: bigint, unclassifiedNs: bigint, };
