// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingAttemptKindCounts } from "./TurnTimingAttemptKindCounts";
import type { TurnTimingGenerationDispositionCounts } from "./TurnTimingGenerationDispositionCounts";
import type { TurnTimingGenerationPurposeAggregate } from "./TurnTimingGenerationPurposeAggregate";
import type { TurnTimingGenerationPurposeCounts } from "./TurnTimingGenerationPurposeCounts";
import type { TurnTimingGenerationReasonCounts } from "./TurnTimingGenerationReasonCounts";

export type TurnTimingCounters = {
/**
 * Logical workflow generations. `model_request_count` remains the
 * authoritative physical provider-attempt aggregate.
 */
logicalGenerationCount: number, generationsByReason: TurnTimingGenerationReasonCounts, generationsByPurpose: TurnTimingGenerationPurposeCounts, generationsByDisposition: TurnTimingGenerationDispositionCounts,
/**
 * Authoritative number of model boundaries suppressed by accepted
 * deterministic-continuation receipts. A receipt whose
 * `suppressed_continuation_count` is N contributes N, not one. Invalid,
 * rejected, and zero-count receipts contribute nothing. This counter is
 * independent of `generations_by_disposition`.
 */
suppressedDeterministicContinuationCount: number,
/**
 * Residual deterministic generation requests proved by the reasoning
 * governor, including requests elided before provider dispatch.
 */
residualDeterministicGenerationCount: number,
/**
 * Continuations drained and recorded by their code-mode owner.
 */
ownerDrainedContinuationCount: number,
/**
 * Exact source projections acknowledged without replaying source text.
 */
sourceExactProjectionReuseCount: number,
/**
 * Physical source reads whose automatically or explicitly supplied
 * conditional identity proved unchanged.
 */
sourceConditionalUnchangedCount: number,
/**
 * Coherent overlapping source intervals removed from model-visible text.
 */
sourceOverlapRangeEliminationCount: bigint,
/**
 * Requested source ranges that did not require an independent physical
 * read because exact or same-operation coverage was reused.
 */
sourcePhysicalRangeAvoidedCount: bigint,
/**
 * Source-specific deterministic continuations drained by the owner.
 */
sourceHostDrainedContinuationCount: number,
/**
 * New source evidence fragments actually exposed to a started model
 * generation.
 */
sourceModelVisibleNewEvidenceCount: bigint,
/**
 * Validation results served from the authoritative validation ledger.
 */
reusedValidationCount: number,
/**
 * Validation tool outputs intentionally suppressed by admission policy.
 */
suppressedValidationOutputCount: number,
/**
 * Ready startup prewarms observed by the first model request.
 */
readyStartupPrewarmCount: number,
/**
 * Completion-review coordinators that observed the ready phase.
 */
completionReviewReadyPhaseCount: number,
/**
 * Completion-review coordinators that observed the terminal phase.
 */
completionReviewTerminalPhaseCount: number,
/**
 * Bounded to the stable purpose enum's cardinality.
 */
purposeAggregates?: Array<TurnTimingGenerationPurposeAggregate>, samePurposeContinuationCount: number, exactRepeatedWaitCount: number, planningGenerationCount: number, planRevisionGenerationCount: number,
/**
 * Aggregate-only architecture-comprehension telemetry. These counters do
 * not contain repository paths, symbols, relationship text, or evidence.
 */
architectureSliceAttemptCount: number, architectureSliceCompleteCount: number, architectureRelationshipCount: bigint, architectureInvariantCount: bigint, architectureMissingRequirementCount: bigint, architectureMaterialUnknownCount: bigint, architectureStaleSnapshotCount: number, architectureToolCallCount: bigint, architectureFilesRead: bigint, architectureBytesRead: bigint, architectureLateRelationshipDiscoveryCount: bigint, planningFixedPointIterationCount: number, planningInvalidationCount: number, planningSemanticEffectCount: number, planningFailureCount: number, failureSignatureCount: number, failureDiagnosisCount: number, attemptsByKind: TurnTimingAttemptKindCounts, modelRequestCount: number, modelRetryCount: number, modelFallbackCount: number, toolCallCount: number, approvalWaitCount: number, permissionWaitCount: number, userInputWaitCount: number, mcpElicitationWaitCount: number, waitOnlyGenerationCount: number, internallyDrainedWaitCount: number, noProgressDirectiveCount: number, provenLoopActivationCount: number, toolOutputTruncationCount: number, toolOutputProjectedTokenCount: bigint, toolOutputArtifactRereadCount: number, toolOutputCanonicalByteCount: bigint, toolOutputCanonicalTokenCount: bigint, toolOutputModelByteCount: bigint, toolOutputModelTokenCount: bigint, toolOutputArtifactCreationCount: number, toolOutputProjectionTruncationCount: number, toolOutputOmittedSectionCount: bigint, toolOutputRecoveryCallCount: number, toolOutputRecoveryRetruncationCount: number, toolOutputRecursiveSpillCount: number, attributableRecoveryGenerationCount: number, truncationInducedContinuationCount: number, invalidTransitionCount: number, clockRegressionCount: number, saturationCount: number, };
