// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic basis used by request token-category accounting.
 *
 * Categories describe the complete logical prompt presented to the model.
 * They do not describe only websocket deltas, newly allocated client memory,
 * uncached provider input, or reconciliation residuals.
 */
export type TurnTimingTokenCategoryBasis = "full_logical_prompt";
