// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingToolCallSource } from "./TurnTimingToolCallSource";

/**
 * Delivery-complete lifecycle for one model-issued or nested tool call.
 *
 * All `*_at_ms` values are monotonic offsets from turn start. A missing
 * boundary means the call ended before that boundary was observed. No tool
 * arguments, output, paths, or nested runtime identifiers are persisted.
 */
export type TurnTimingToolCall = { callId: string, toolName: string, source: TurnTimingToolCallSource, generationIndex: number | null, acceptedAtMs: number | null, firstPollAtMs: number | null, parallelGateAdmittedAtMs: number | null, handlerEntryAtMs: number | null, handlerExitAtMs: number | null,
/**
 * The tool result has been collected into the host relay, before any
 * post-handler evidence, projection, persistence, or delivery work.
 */
outputCollectedAtMs: number | null, processSpawnedAtMs: number | null, processExitedAtMs: number | null, deliveredAtMs: number | null,
/**
 * The next model generation began after this result was delivered.
 */
modelResumedAtMs: number | null, itemToFirstPollMs: number | null, parallelGateWaitMs: number | null, authorizationStateCoordinationMs: number | null, handlerDurationMs: number | null, workspaceEvidenceBeforeMs: number | null, workspaceEvidenceAfterMs: number | null, preToolHookMs: number | null, postToolHookMs: number | null, outputProjectionMs: number | null, historyPersistenceMs: number | null, postHandlerMs: number | null, totalDurationMs: number | null, eager: boolean, processAliveAtDelivery: boolean, };
