// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingAttemptKind } from "./TurnTimingAttemptKind";
import type { TurnTimingGenerationReason } from "./TurnTimingGenerationReason";

export type TurnTimingModelRequest = {
/**
 * Zero-based logical generation owning this physical provider attempt.
 */
generationIndex: number, generationReason: TurnTimingGenerationReason, attemptKind: TurnTimingAttemptKind, isContinuation: boolean,
/**
 * Directly observed model-stream wait for this physical attempt.
 */
modelStreamWaitNs: bigint,
/**
 * Tool calls emitted by this generation. Recorded on its primary attempt.
 */
toolCallCount: number, dispatchMs?: number | null, firstModelOutputMs?: number | null, completedMs?: number | null, };
