// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingAttemptKind } from "./TurnTimingAttemptKind";
import type { TurnTimingGenerationDisposition } from "./TurnTimingGenerationDisposition";
import type { TurnTimingGenerationPurpose } from "./TurnTimingGenerationPurpose";
import type { TurnTimingGenerationReason } from "./TurnTimingGenerationReason";
import type { TurnTimingProgressKind } from "./TurnTimingProgressKind";
import type { TurnTimingProviderTokenUsage } from "./TurnTimingProviderTokenUsage";
import type { TurnTimingRequestTokenCategories } from "./TurnTimingRequestTokenCategories";

export type TurnTimingModelRequest = {
/**
 * Zero-based logical generation owning this physical provider attempt.
 */
generationIndex: number, generationReason: TurnTimingGenerationReason,
/**
 * Stable workflow purpose for the logical generation. Physical retries
 * inherit this value from their owning generation.
 */
generationPurpose?: TurnTimingGenerationPurpose, disposition: TurnTimingGenerationDisposition,
/**
 * A redacted hash of only the structured state relevant to this request.
 */
relevantStateFingerprint?: string, progressKinds?: Array<TurnTimingProgressKind>, nextStructuredActionChanged: boolean, unchangedRelevantState: boolean, attemptKind: TurnTimingAttemptKind, isContinuation: boolean,
/**
 * Directly observed model-stream wait for this physical attempt.
 */
modelStreamWaitNs: bigint,
/**
 * Tool calls emitted by this generation. Recorded on its primary attempt.
 */
toolCallCount: number, outputTokens: bigint, reasoningOutputTokens: bigint,
/**
 * Provider-reported usage for this physical attempt. Missing usage stays
 * null, including failed attempts for which the provider reported none.
 */
tokenUsage?: TurnTimingProviderTokenUsage,
/**
 * Aggregate-only full logical prompt accounting. No prompt text,
 * repository paths, tool arguments, or hashes are persisted here.
 */
requestTokenCategories?: TurnTimingRequestTokenCategories, dispatchMs?: number | null, firstModelOutputMs?: number | null, completedMs?: number | null, };
