// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingProgressKind = "new_input" | "new_named_evidence" | "source_closure" | "workspace_mutation" | "validation_result" | "plan_change" | "failure_observation" | "completion_state" | "structured_action_change";
