// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingSourceSectionCategoryCounts = { primaryImplementation: number, directCallers: number, focusedTests: number, contracts: number, generatedRelationships: number, otherSourceContext: number, coreState: number, };
