// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingMilestones = {
/**
 * Time from turn start until the first user input begins durable recording.
 */
userInputRecordedMs: number | null,
/**
 * Time from turn start until the first tool call is accepted for dispatch.
 */
firstToolAcceptedMs: number | null,
/**
 * Time from turn start until the first tool call passes the parallel gate.
 */
firstToolGateAdmittedMs: number | null,
/**
 * Time from turn start until the first authorized tool handler is entered.
 */
firstToolHandlerEntryMs: number | null,
/**
 * Time from turn start until the first non-control tool is accepted for dispatch.
 */
firstUsefulToolAcceptedMs: number | null,
/**
 * Time from turn start until the first non-control tool passes the parallel gate.
 */
firstUsefulToolGateAdmittedMs: number | null,
/**
 * Time from turn start until the first authorized non-control tool handler is entered.
 */
firstUsefulActionMs: number | null,
/**
 * Time from turn start until the first non-control tool completes successfully.
 */
firstSuccessfulUsefulActionMs: number | null, firstModelOutputMs: number | null, firstActionableOutputMs: number | null, firstVisibleOutputMs: number | null, firstAgentMessageMs: number | null, };
