// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SamplingGenerationId } from "../SamplingGenerationId";
import type { ToolExecutionId } from "../ToolExecutionId";
import type { TurnTimingToolCallSource } from "./TurnTimingToolCallSource";

/**
 * Payload-free identity for one accepted tool execution in the terminal
 * closure ledger.
 */
export type TurnTimingToolCallIdentity = { callId: string, executionId: ToolExecutionId, source: TurnTimingToolCallSource, parentCallId?: string, samplingGenerationId: SamplingGenerationId, };
