// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfacedToolResult } from "./SurfacedToolResult";
import type { ThreadItem } from "./ThreadItem";
import type { TurnError } from "./TurnError";
import type { TurnItemsView } from "./TurnItemsView";
import type { TurnStatus } from "./TurnStatus";
import type { TurnTiming } from "./TurnTiming";

export type Turn = {/**
 * Identifier for this turn. Codex-generated turn IDs are UUIDv7.
 */
id: string, /**
 * Thread items currently included in this turn payload.
 */
items: Array<ThreadItem>, /**
 * Describes how much of `items` has been loaded for this turn.
 */
itemsView: TurnItemsView, status: TurnStatus, /**
 * Only populated when the Turn's status is failed.
 */
error: TurnError | null, /**
 * Unix timestamp (in seconds) when the turn started.
 */
startedAt: number | null, /**
 * Unix timestamp (in seconds) when the turn completed.
 */
completedAt: number | null, /**
 * Duration between turn start and completion in milliseconds, if known.
 */
durationMs: number | null, /**
 * Immutable wall-clock profile persisted at the terminal turn boundary.
 */
timing?: TurnTiming, /**
 * Authoritative typed tool result surfaced when the turn terminalized.
 */
surfacedResult?: SurfacedToolResult};
