// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingAttemptKindCounts } from "./TurnTimingAttemptKindCounts";
import type { TurnTimingGenerationDispositionCounts } from "./TurnTimingGenerationDispositionCounts";
import type { TurnTimingGenerationPurposeAggregate } from "./TurnTimingGenerationPurposeAggregate";
import type { TurnTimingGenerationPurposeCounts } from "./TurnTimingGenerationPurposeCounts";
import type { TurnTimingGenerationReasonCounts } from "./TurnTimingGenerationReasonCounts";

export type TurnTimingCounters = {
/**
 * Logical workflow generations. `model_request_count` remains the
 * authoritative physical provider-attempt aggregate.
 */
logicalGenerationCount: number, generationsByReason: TurnTimingGenerationReasonCounts, generationsByPurpose: TurnTimingGenerationPurposeCounts, generationsByDisposition: TurnTimingGenerationDispositionCounts,
/**
 * Authoritative number of model boundaries suppressed by accepted
 * deterministic-continuation receipts. A receipt whose
 * `suppressed_continuation_count` is N contributes N, not one. Invalid,
 * rejected, and zero-count receipts contribute nothing. This counter is
 * independent of `generations_by_disposition`.
 */
suppressedDeterministicContinuationCount: number,
/**
 * Residual deterministic generation requests proved by turn execution.
 * Null means production execution control does not measure this counter.
 */
residualDeterministicGenerationCount: number | null,
/**
 * Continuations drained and recorded by their code-mode owner.
 */
ownerDrainedContinuationCount: number,
/**
 * Validation commands that executed.
 */
executedValidationCount: number,
/**
 * Total wall-clock nanoseconds spent in validation commands that executed.
 */
executedValidationDurationNs: bigint,
/**
 * Validation tool outputs intentionally suppressed by admission policy.
 */
suppressedValidationOutputCount: number,
/**
 * Ready startup prewarms observed by the first model request.
 */
readyStartupPrewarmCount: number,
/**
 * Tool results the aggregate output budget dropped across every request
 * this turn actually sent. Preparing an unchanged projection again adds
 * nothing; only a dispatched request contributes.
 */
toolOutputBudgetDropCount: number,
/**
 * Tokens those dropped results would have occupied.
 */
toolOutputBudgetDroppedTokenCount: bigint,
/**
 * Bounded to the stable purpose enum's cardinality.
 */
purposeAggregates?: Array<TurnTimingGenerationPurposeAggregate>, samePurposeContinuationCount: number,
/**
 * Wait generations sharing coarse revisions; this does not establish that
 * the wait action, cursor, or owner state repeated.
 */
waitGenerationsWithSameRevisionCount: number, planningGenerationCount: number, planRevisionGenerationCount: number, planningFixedPointIterationCount: number, planningInvalidationCount: number, planningSemanticEffectCount: number, planningFailureCount: number, failureSignatureCount: number, failureDiagnosisCount: number, attemptsByKind: TurnTimingAttemptKindCounts, modelRequestCount: number, modelRetryCount: number, modelFallbackCount: number, toolCallCount: number, approvalWaitCount: number, permissionWaitCount: number, userInputWaitCount: number, mcpElicitationWaitCount: number, waitOnlyGenerationCount: number, internallyDrainedWaitCount: number, noProgressDirectiveCount: number, provenLoopActivationCount: number, toolRouterReuseCount: number, toolRouterRebuildCount: number, projectionSourceDependenciesReuseCount: number, projectionSourceDependenciesFallbackCount: number, toolOutputTruncationCount: number, toolOutputProjectedTokenCount: bigint, toolOutputArtifactRereadCount: number, toolOutputCanonicalByteCount: bigint, toolOutputCanonicalTokenCount: bigint, toolOutputModelByteCount: bigint, toolOutputModelTokenCount: bigint, toolOutputArtifactCreationCount: number, toolOutputArtifactReuseCount: number, toolOutputProjectionTruncationCount: number, toolOutputOmittedSectionCount: bigint, toolOutputRecoveryCallCount: number, toolOutputRecoveryRetruncationCount: number, toolOutputRecursiveSpillCount: number,
/**
 * Tool-result generations immediately following an observed
 * `read_tool_output` recovery transaction. This is independent of
 * whether the recovered projection was truncated again.
 */
attributableRecoveryGenerationCount: number,
/**
 * Tool-result generations immediately following provider-visible output
 * that actually omitted or truncated canonical tool information.
 */
truncationInducedContinuationCount: number, invalidTransitionCount: number, clockRegressionCount: number, saturationCount: number, };
