// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeterministicContinuationClass } from "./DeterministicContinuationClass";
import type { DeterministicContinuationHostAction } from "./DeterministicContinuationHostAction";

export type TurnTimingDeterministicContinuationReceipt = { class: DeterministicContinuationClass, resourceIdentityHash: string, stateRevision: string, hostAction: DeterministicContinuationHostAction, wireIdentity: string, suppressedContinuationCount: number, };
