// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingProviderTokenUsage = { inputTokens: bigint, cachedInputTokens: bigint, visibleOutputTokens: bigint, reasoningTokens: bigint, totalTokens: bigint, };
