// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingExclusive = { modelOnlyNs: bigint, toolOnlyNs: bigint, modelPlusToolNs: bigint, interactiveOnlyWaitNs: bigint, interactivePlusMachineNs: bigint, retryOnlyNs: bigint, orchestrationNs: bigint, standaloneWorkNs: bigint, finalizationNs: bigint, unclassifiedNs: bigint, };
