// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingGenerationPurpose } from "./TurnTimingGenerationPurpose";

export type TurnTimingGenerationPurposeAggregate = { purpose: TurnTimingGenerationPurpose, generations: number, modelStreamWaitNs: bigint,
/**
 * Sum of dispatch-to-first-actionable-output latency for requests where
 * an actionable output was observed.
 */
decisionLatencyNs: bigint, decisionReadyRequests: number, toolCalls: number,
/**
 * Sum of per-generation unioned tool-active durations. Parallel tools
 * within one generation are not double-counted.
 */
toolActiveUnionNs: bigint, outputTokens: bigint, reasoningOutputTokens: bigint, inputTokens: bigint, cachedInputTokens: bigint, visibleOutputTokens: bigint, totalTokens: bigint, };
