// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingPostDiscoveryRequest = { totalProviderInputTokens: bigint, cachedInputTokens: bigint, newlyInjectedDiscoveryResultTokens: bigint, discoveryResultCells: number, discoveryModelBoundaryCount: number,
/**
 * `(provider input / injected result tokens) * 1_000_000` when defined.
 */
replayAmplificationMicros?: number | null, };
