// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingLocal = { preparationUnionNs: bigint, planningUnionNs: bigint, compactionUnionNs: bigint, persistenceUnionNs: bigint, serializationUnionNs: bigint, routerBuildUnionNs: bigint, startupPrewarmWaitUnionNs: bigint, executorReadinessWaitUnionNs: bigint, };
