// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingGenerationReasonCounts = { initial: number, toolContinuation: number, completionReview: number, completionRepairRereview: number, compaction: number, subagent: number, other: number, };
