// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingGenerationPurpose = "initial" | "source_discovery" | "source_interpretation" | "implementation" | "wait" | "failure_diagnosis" | "validation_launch" | "validation_interpretation" | "repair" | "agent_coordination" | "deterministic_tool_continuation" | "compaction_recovery" | "terminal";
