// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingMilestones = {
/**
 * Time from turn start until the first user input begins durable recording.
 */
userInputRecordedMs: number | null,
/**
 * Time from turn start until the first tool call is accepted for dispatch.
 */
firstToolAcceptedMs: number | null,
/**
 * Time from turn start until the first tool call passes the parallel gate.
 */
firstToolGateAdmittedMs: number | null,
/**
 * Time from turn start until the first authorized tool handler is entered.
 */
firstToolHandlerEntryMs: number | null,
/**
 * Time from turn start until the first domain-work tool is accepted for dispatch.
 */
firstUsefulToolAcceptedMs: number | null,
/**
 * Time from turn start until the first domain-work tool passes the parallel gate.
 */
firstUsefulToolGateAdmittedMs: number | null,
/**
 * Time from turn start until the first authorized domain-work tool handler is entered.
 */
firstUsefulActionMs: number | null,
/**
 * Time from turn start until the first domain-work tool completes successfully.
 */
firstSuccessfulUsefulActionMs: number | null,
/**
 * Time from turn start until the first authorized control/plumbing tool handler is entered.
 */
firstInfrastructureActionMs: number | null,
/**
 * Time from turn start until the first authorized tool-schema discovery handler is entered.
 */
firstToolDiscoveryActionMs: number | null,
/**
 * Time from turn start until the first authorized domain-work handler is entered.
 */
firstDomainActionMs: number | null,
/**
 * Time from turn start until the first domain-work tool completes successfully.
 */
firstSuccessfulDomainActionMs: number | null, firstModelOutputMs: number | null, firstActionableOutputMs: number | null, firstVisibleOutputMs: number | null, firstAgentMessageMs: number | null, };
