// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeterministicContinuationClass } from "./DeterministicContinuationClass";
import type { DeterministicContinuationHostAction } from "./DeterministicContinuationHostAction";
import type { TurnTimingProviderTokenUsage } from "./TurnTimingProviderTokenUsage";

export type TurnTimingDeterministicContinuationReceipt = { class: DeterministicContinuationClass, resourceIdentityHash: string, stateRevision: string, hostAction: DeterministicContinuationHostAction, suppressedContinuationCount: number,
/**
 * Populated only by an explicit paired counterfactual measurement. Normal
 * runtime receipts leave this absent rather than estimating savings.
 */
avoidedTokenUsage?: TurnTimingProviderTokenUsage, };
