// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingCounters } from "./TurnTimingCounters";
import type { TurnTimingExclusive } from "./TurnTimingExclusive";
import type { TurnTimingLocal } from "./TurnTimingLocal";
import type { TurnTimingMilestones } from "./TurnTimingMilestones";
import type { TurnTimingUnions } from "./TurnTimingUnions";

/**
 * Immutable wall-clock profile captured at the core terminal boundary.
 *
 * `exclusive` is the canonical elapsed-time partition. Values in `unions`
 * and `local` may overlap and must not be added to that partition.
 */
export type TurnTiming = { schemaVersion: number, profileValid: boolean, classificationComplete: boolean, startedAtUnixMs?: number | null, completedAtUnixMs?: number | null, inclusiveDurationNs: bigint, inclusiveDurationMs: bigint,
/**
 * Inclusive duration minus only the interactive-only wait partition.
 */
machineDurationNs: bigint, machineDurationMs: bigint, exclusive: TurnTimingExclusive, unions: TurnTimingUnions, local: TurnTimingLocal, milestones: TurnTimingMilestones, counters: TurnTimingCounters, };
