// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTimingGenerationPurpose } from "./TurnTimingGenerationPurpose";

export type TurnTimingGenerationPurposeAggregate = { purpose: TurnTimingGenerationPurpose, generations: number, modelStreamWaitNs: bigint, toolCalls: number, outputTokens: bigint, reasoningOutputTokens: bigint, inputTokens: bigint, cachedInputTokens: bigint, visibleOutputTokens: bigint, totalTokens: bigint, };
