// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextSampleBlockReason } from "../NextSampleBlockReason";
import type { SamplingGenerationId } from "../SamplingGenerationId";
import type { ToolExecutionId } from "../ToolExecutionId";
import type { ToolLifecycleTimerWait } from "../ToolLifecycleTimerWait";
import type { TurnTimingToolLifecycleEvent } from "../TurnTimingToolLifecycleEvent";
import type { TurnTimingToolCallSource } from "./TurnTimingToolCallSource";

/**
 * Relay and persistence lifecycle for one model-issued or nested tool call.
 *
 * All `*_at_ms` values are monotonic offsets from turn start. A missing
 * boundary means the call ended before that boundary was observed. No tool
 * arguments, output, or paths are persisted; nested identifiers are opaque
 * correlation keys only.
 */
export type TurnTimingToolCall = { callId: string,
/**
 * Model-visible outer tool call that owns this nested call, when any.
 */
parentCallId?: string,
/**
 * Runtime cell that issued this nested tool request, when any.
 */
parentCellId?: string,
/**
 * Code-mode's payload-free per-cell invocation id, when any.
 */
runtimeToolCallId?: string, toolName: string, source: TurnTimingToolCallSource, executionId: ToolExecutionId, samplingGenerationId: SamplingGenerationId,
/**
 * Payload-free terminal classification reported by the tool runtime.
 */
outcome?: string, generationIndex: number | null, acceptedAtMs: number | null, firstPollAtMs: number | null, parallelGateAdmittedAtMs: number | null, handlerEntryAtMs: number | null, handlerExitAtMs: number | null,
/**
 * The tool result has been collected into the host relay, before any
 * post-handler evidence, projection, persistence, or delivery work.
 */
outputCollectedAtMs: number | null, processSpawnedAtMs: number | null, processExitedAtMs: number | null,
/**
 * Historical relay-completion boundary. This predates persistence timing
 * and therefore does not prove that the output reached conversation
 * history or the rollout recorder.
 */
deliveredAtMs: number | null,
/**
 * The direct tool output was committed to model-visible conversation
 * history. Durable rollout persistence is tracked independently by the
 * tool-closure ledger. Nested code-mode calls are represented by the outer
 * direct tool output and leave this absent.
 */
outputModelVisibleAtMs: number | null,
/**
 * The next model generation began after this result became model-visible.
 */
modelResumedAtMs: number | null,
/**
 * Monotonic latency from the host proving that sampling is unblocked to
 * the provider request reaching its transport dispatch boundary.
 */
readyToSampleToDispatchNs: number | null, itemToFirstPollMs: number | null, parallelGateWaitMs: number | null, authorizationStateCoordinationMs: number | null, handlerDurationMs: number | null, workspaceEvidenceBeforeMs: number | null,
/**
 * Whether the pre-handler workspace identity came from the latest
 * authoritative capture instead of running a fresh capture.
 */
workspaceEvidenceBeforeCacheHit: boolean | null,
/**
 * Git dependencies that crossed the bounded capture deadline during a
 * fresh pre-handler workspace capture.
 */
workspaceEvidenceBeforeTimedOutGitDependencies: Array<string>, workspaceEvidenceAfterMs: number | null, preToolHookMs: number | null, postToolHookMs: number | null, outputProjectionMs: number | null, historyPersistenceMs: number | null, postHandlerMs: number | null, totalDurationMs: number | null, eager: boolean, processAliveAtDelivery: boolean,
/**
 * The exec handler reached its post-cleanup process-store observation.
 */
execCleanupStateObserved: boolean,
/**
 * A retained running process is expected only when the response returned
 * a background process identifier for a later `write_stdin` call.
 */
backgroundProcessExpected: boolean,
/**
 * The process manager still retained this call after foreground cleanup.
 */
runningProcessAfterCleanup: boolean,
/**
 * Exact event-site lifecycle records. Older timestamp fields remain as
 * compatibility projections of these boundaries.
 */
lifecycleEvents: Array<TurnTimingToolLifecycleEvent>, timerWaits: Array<ToolLifecycleTimerWait>, retryCount: number, reentryCount: number, nextSampleBlockReason: NextSampleBlockReason, };
