// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnTimingGenerationPurposeCounts = { initialReasoning: number, implementationDecision: number, wait: number, failureDiagnosis: number, validationInterpretation: number, repair: number, coordination: number, artifactContinuation: number, compactionRecovery: number, terminalCompletionReasoning: number, };
