// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { PermissionProfile } from "../PermissionProfile";
import type { WindowsSandboxSetupMode } from "./WindowsSandboxSetupMode";

export type WindowsSandboxSetupStartParams = { mode: WindowsSandboxSetupMode, cwd?: AbsolutePathBuf | null,
/**
 * Named permission profile to resolve on the app-server before setup.
 */
permissionProfileId?: string,
/**
 * Inline permission profile used when setup precedes persisting a preset.
 */
permissionProfile?: PermissionProfile<AbsolutePathBuf>, };
