mod cargo_cache;
mod ci;
mod context;
mod finalize;
mod json;
mod model;
mod planner;
mod runner;
mod secure_result;
mod snapshot;

pub use cargo_cache::CargoCacheDisposition;
pub use cargo_cache::CargoCacheError;
pub use cargo_cache::CargoMetadataRequest;
pub use cargo_cache::CargoMetadataResult;
pub use cargo_cache::load_cargo_metadata;
pub use ci::CiDecisionArtifact;
pub use ci::CiDecisionBody;
pub use ci::CiDecisionError;
pub use ci::CiDecisionOutputs;
pub use ci::MatrixPlan;
pub use ci::WorkflowDecision;
pub use ci::build_ci_decision;
pub use ci::build_ci_decision_from_metadata;
pub use ci::decision_id;
pub use ci::verify_ci_decision_artifact;
pub use ci::write_ci_decision_artifact;

pub use finalize::finalize_plan;
pub use json::JsonContractError;
pub use json::render_human;
pub use json::serialize_legacy_error;
pub use json::serialize_legacy_v1;
pub use json::serialize_v2_finalized;
pub use json::serialize_v2_plan;
pub use model::CommandArgV2;
pub use model::CommandResultV2;
pub use model::CommandSpecV2;
pub use model::FinalizedCommandResult;
pub use model::FinalizedVerification;
pub use model::LaunchErrorKind;
pub use model::LogState;
pub use model::PlanEnvelopeV2;
pub use model::PlanMode;
pub use model::PlanRequest;
pub use model::RawPath;
pub use model::RepositorySnapshot;
pub use model::ScopeV2;
pub use model::SkippedDecision;
pub use model::SnapshotRecord;
pub use model::SnapshotSource;
pub use model::Verdict;
pub use planner::plan_verification;
pub use runner::execute_plan;
pub use runner::random_hex_128;
pub use snapshot::CommitComparisonMode;
pub use snapshot::SnapshotError;
