[package]
name = "codex-process-hardening"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codex_process_hardening"
path = "src/lib.rs"
doctest = false

[dependencies]
windows-sys = { workspace = true, features = [
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }

[lints]
workspace = true
