use anyhow::Context;
use codex_git_utils::GitBaselineDiff;
use codex_git_utils::diff_since_latest_init;
use codex_git_utils::ensure_git_baseline_repository;
use codex_git_utils::reset_git_repository;
use std::path::Path;

use crate::generated_files::write_generated_file;

/// Prepares the memory directory for git-baseline diffing.
///
/// This keeps an existing usable `.git/` baseline intact. It initializes a new git baseline when the
/// metadata is missing or unusable, keeping existing files as pending additions. It removes stale
/// generated `phase2_workspace_diff.md` files so the next diff excludes previous prompt artifacts.
pub async fn prepare_memory_workspace(root: &Path) -> anyhow::Result<()> {
    tokio::fs::create_dir_all(root)
        .await
        .with_context(|| format!("create memory workspace {}", root.display()))?;
    remove_workspace_diff(root).await?;
    ensure_git_baseline_repository(root).await?;
    Ok(())
}

/// Returns the current workspace diff after removing any stale generated diff artifact.
///
/// The removed file is only `phase2_workspace_diff.md`; memory artifacts and `.git/` metadata are
/// left intact.
pub async fn memory_workspace_diff(root: &Path) -> anyhow::Result<GitBaselineDiff> {
    remove_workspace_diff(root).await?;
    diff_since_latest_init(root).await
}

/// Writes `phase2_workspace_diff.md` with a bounded git-style diff from the current baseline.
pub async fn write_workspace_diff(root: &Path, diff: &GitBaselineDiff) -> anyhow::Result<()> {
    let path = root.join(crate::workspace_diff::FILENAME);
    let contents = render_workspace_diff_file(diff);
    write_generated_file(&path, &contents)
        .await
        .with_context(|| format!("write memory workspace diff file {}", path.display()))
}

/// Marks the current memory root as the new baseline.
///
/// The generated diff file is removed before resetting the baseline so deleted memory content is
/// not retained in the prompt artifact or in unreachable git objects.
pub async fn reset_memory_workspace_baseline(root: &Path) -> anyhow::Result<()> {
    remove_workspace_diff(root).await?;
    reset_git_repository(root).await
}

/// Removes the generated `phase2_workspace_diff.md` prompt artifact.
///
/// This does not remove `.git/`, reset the baseline, or delete memory content. It is used before
/// diffing and before baseline reset so the generated diff file itself is not treated as memory
/// workspace input.
pub(super) async fn remove_workspace_diff(root: &Path) -> anyhow::Result<()> {
    let path = root.join(crate::workspace_diff::FILENAME);
    match tokio::fs::remove_file(&path).await {
        Ok(()) => Ok(()),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(err) => Err(err)
            .with_context(|| format!("remove memory workspace diff file {}", path.display())),
    }
}

fn render_workspace_diff_file(diff: &GitBaselineDiff) -> String {
    const PARTIAL: &str = "\nChange coverage is partial. Run `git status --short --untracked-files=all` to enumerate all paths, including deletions, then inspect omitted paths and their baseline contents with targeted Git reads before consolidating.\n";
    const SUFFIX: &str =
        "\n[workspace diff truncated; inspect omitted changes before consolidating]\n```\n";
    let mut rendered = String::from(
        "# Memory Workspace Diff\n\n\
         Generated by Codex before Phase 2 memory consolidation. Read this file first and do not edit it.\n\n\
         If existing consolidated memory files appear as additions, the baseline was rebuilt: review all current inputs and reconcile existing memories, including unsupported memories.\n\n\
         ## Status\n",
    );

    if !diff.has_changes() {
        rendered.push_str("- none\n");
        return rendered;
    }

    // Reserve framing and an explicit warning within the overall artifact budget.
    let limit = crate::workspace_diff::MAX_BYTES - PARTIAL.len() - SUFFIX.len() - 32;
    for change in &diff.changes {
        if rendered.len() + change.path.len() + 5 > limit {
            rendered.push_str(PARTIAL);
            return rendered;
        }
        rendered.push_str(&format!("- {} {}\n", change.status.label(), change.path));
    }
    rendered.push_str("\n## Diff\n\n```diff\n");
    let remaining =
        crate::workspace_diff::MAX_BYTES - rendered.len() - SUFFIX.len() - PARTIAL.len();
    if diff.unified_diff.len() > remaining {
        let boundary = diff.unified_diff.floor_char_boundary(remaining);
        rendered.push_str(&diff.unified_diff[..boundary]);
        rendered.push_str(SUFFIX);
        rendered.push_str(PARTIAL);
    } else {
        rendered.push_str(&diff.unified_diff);
        if !rendered.ends_with('\n') {
            rendered.push('\n');
        }
        rendered.push_str("```\n");
    }
    rendered
}

#[cfg(test)]
#[path = "workspace_tests.rs"]
mod tests;
