use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let Some(proto_dir_arg) = std::env::args_os().nth(1) else {
        eprintln!("Usage: generate-proto <proto-dir>");
        std::process::exit(1);
    };

    let proto_dir = PathBuf::from(proto_dir_arg);
    let proto_file = proto_dir.join("codex.thread_config.v1.proto");

    tonic_prost_build::configure()
        .build_client(true)
        .build_server(true)
        .out_dir(&proto_dir)
        .compile_protos(&[proto_file], &[proto_dir.clone()])?;

    // Keep the module-level allowance reproducible when regenerating tonic's
    // service code, rather than requiring a manual edit to generated Rust.
    let generated = proto_dir.join("codex.thread_config.v1.rs");
    let contents = std::fs::read_to_string(&generated)?;
    std::fs::write(
        generated,
        contents.replacen(
            "// This file is @generated by prost-build.\n",
            "// This file is @generated by prost-build.\n#![allow(clippy::trivially_copy_pass_by_ref)]\n\n",
            1,
        ),
    )?;

    Ok(())
}
