// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandExecutionOutputMetadata = {
/**
 * Process termination and output drain are independent observations.
 */
process_exited: boolean, output_drained: boolean, aggregated_output_is_exact: boolean, streams_are_exact: boolean, decoding_lossy: boolean, display_reduced: boolean,
/**
 * Conservative owner-classified search miss; the raw exit code remains 1.
 */
search_no_match: boolean,
/**
 * Harness/observation failure, not a program exit status or stderr bytes.
 */
failure_cause: string | null,
/**
 * Existing retained-output locator, when available at delivery time.
 */
raw_output_artifact_id: string | null, };
