// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FuzzyFileSearchResult } from "./FuzzyFileSearchResult";

export type FuzzyFileSearchSessionUpdatedNotification = { sessionId: string, query: string, files: Array<FuzzyFileSearchResult>,
/**
 * Matches found among scanned entries, before the result limit is applied.
 * Zero when the query is empty and results are suppressed.
 */
totalMatchCount: number,
/**
 * Number of indexed files and directories, including entries that did not match.
 */
scannedFileCount: number,
/**
 * True only after scanning finishes without omitting paths. A completed
 * notification with this still false indicates an incomplete traversal.
 */
walkComplete: boolean, };
