// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FuzzyFileSearchResult } from "./FuzzyFileSearchResult";

export type FuzzyFileSearchResponse = { files: Array<FuzzyFileSearchResult>,
/**
 * Matches found among scanned entries, before the result limit is applied.
 */
totalMatchCount: number,
/**
 * Number of indexed files and directories, including entries that did not match.
 */
scannedFileCount: number,
/**
 * False if scanning was skipped or paths were omitted due to limits, cancellation, or errors.
 */
walkComplete: boolean, };
