// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { ServerBuildInfo } from "./ServerBuildInfo";
import type { ServerCapabilities } from "./ServerCapabilities";
import type { ServerLocalWatermark } from "./ServerLocalWatermark";
import type { ServerRuntimeInfo } from "./ServerRuntimeInfo";

export type InitializeResponse = { userAgent: string,
/**
 * Absolute path to the server's $CODEX_HOME directory.
 */
codexHome: AbsolutePathBuf,
/**
 * Platform family for the running app-server target, for example
 * `"unix"` or `"windows"`.
 */
platformFamily: string,
/**
 * Operating system for the running app-server target, for example
 * `"macos"`, `"linux"`, or `"windows"`.
 */
platformOs: string,
/**
 * Build metadata for the running app-server binary.
 */
buildInfo?: ServerBuildInfo,
/**
 * Runtime provenance for the running app-server process.
 */
runtimeInfo?: ServerRuntimeInfo,
/**
 * Effective app-server capabilities advertised at initialize time.
 */
serverCapabilities?: ServerCapabilities,
/**
 * Local fork watermark for desktop-visible runtime proof.
 */
localWatermark?: ServerLocalWatermark, };
