// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { FileSystemSandboxEntry } from "./FileSystemSandboxEntry";

/**
 * Filesystem permissions for profiles where Codex owns sandbox construction.
 */
export type ManagedFileSystemPermissions<PathType = AbsolutePathBuf> = { "type": "restricted", entries: Array<FileSystemSandboxEntry<PathType>>, glob_scan_max_depth?: number, } | { "type": "unrestricted" };
