// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NextSampleBlockReason = "waiting_for_tool" | "waiting_for_delivery" | "waiting_for_gate" | "waiting_for_process_cleanup" | "ready_to_sample";
