// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ReasoningPolicyPhase } from "./ReasoningPolicyPhase";
import type { ReasoningPolicySource } from "./ReasoningPolicySource";
import type { ReasoningPolicyTrigger } from "./ReasoningPolicyTrigger";

export type ReasoningPolicySnapshot = { sequence: bigint,
/**
 * Unix timestamp in milliseconds.
 */
timestamp: bigint, phase: ReasoningPolicyPhase, configuredEffort: ReasoningEffort | null, effectiveEffort: ReasoningEffort | null, requestEffort: ReasoningEffort | null, source: ReasoningPolicySource, model: string, trigger: ReasoningPolicyTrigger, };
