// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response event from the agent
 * NOTE: Make sure none of these values have optional types, as it will mess up the extension code-gen.
 * The exact request policy used for one model stream attempt. This is protocol
 * state so rollout reconstruction and late-attaching clients observe the same
 * decision as live consumers.
 */
export type ReasoningPolicyPhase = "orient" | "inspect" | "implement" | "verify" | "diagnose" | "finalize";
