// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningPolicySnapshot } from "./ReasoningPolicySnapshot";

/**
 * Bounded, durable per-turn reasoning-policy history.
 */
export type ReasoningPolicyHistory = { turnId: string, entries: Array<ReasoningPolicySnapshot>, totalEntries: bigint, truncated: boolean, };
