// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReasoningPolicyTrigger = "user_input" | "read_only_tool_success" | "workspace_mutation" | "tool_failed" | "tool_blocked" | "tool_timed_out" | "tool_cancelled" | "validation_passed" | "validation_failed" | "validation_timed_out" | "plan_updated" | "host_override";
