// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestUserInputDisposition = "answered" | "timed_out" | "skipped" | "interrupted" | "transport_error";
