// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { ServerPackageLayout } from "./ServerPackageLayout";
import type { ServerRuntimeWarning } from "./ServerRuntimeWarning";

export type ServerRuntimeInfo = { executablePath: AbsolutePathBuf | null, installMethod: string, packageLayout: ServerPackageLayout | null, expectedLocalBinaryPath: AbsolutePathBuf | null, localBinaryMatch: boolean | null, warnings: Array<ServerRuntimeWarning>, };
