// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolLifecycleBoundary = "request_created" | "admitted" | "handler_start" | "process_spawn" | "process_exit" | "handler_return" | "relay_enqueue" | "relay_delivery" | "next_model_sample_start";
