// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queue and waiter state captured at a lifecycle boundary.
 */
export type ToolLifecycleContext = { relayQueueDepth: number, parallelGateWaiterCount: number, samplingGateWaiterCount: number, processOutputWaiterCount: number, activeToolCount: number, };
