// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolLifecycleBoundary = "request_created" | "resource_resolution_start" | "resource_resolution_end" | "diff_tracker_wait_start" | "diff_tracker_wait_end" | "workspace_gate_wait_start" | "workspace_gate_wait_end" | "evidence_tracker_wait_start" | "evidence_tracker_wait_end" | "admitted" | "handler_start" | "process_spawn" | "process_exit" | "handler_return" | "relay_enqueue" | "relay_delivery" | "next_model_sample_start";
