// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolLifecycleWakeReason } from "./ToolLifecycleWakeReason";

/**
 * Attribution for a bounded or sticky lifecycle wait.
 */
export type ToolLifecycleTimerWait = { waitKind: string, requestedTimeoutMs: number | null, effectiveTimeoutMs: number | null, deadlineAtMs: number | null, wakeReason: ToolLifecycleWakeReason, sequence: number, };
