// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolLifecycleBoundary } from "./ToolLifecycleBoundary";
import type { ToolLifecycleContext } from "./ToolLifecycleContext";

/**
 * Exact event-site timestamp from the turn's single monotonic clock.
 */
export type TurnTimingToolLifecycleEvent = { boundary: ToolLifecycleBoundary, atMs: bigint, context: ToolLifecycleContext, retryCount: number, reentryCount: number, };
