//! Central defaults for fork-local coding completeness budgets.

pub const PROJECT_DOC_MAX_BYTES: usize = 96 * 1024;

pub const SKILL_METADATA_CHAR_BUDGET: usize = 16_000;
pub const SKILL_METADATA_CONTEXT_WINDOW_PERCENT: usize = 4;
pub const SKILL_DESCRIPTION_TRUNCATION_WARNING_THRESHOLD_CHARS: usize = 100;
pub const APPROX_BYTES_PER_TOKEN: usize = 4;
pub const SKILL_MAX_NAME_LEN: usize = 64;
pub const SKILL_MAX_QUALIFIED_NAME_LEN: usize = 128;
pub const SKILL_MAX_DESCRIPTION_LEN: usize = 1024;
pub const SKILL_MAX_SHORT_DESCRIPTION_LEN: usize = SKILL_MAX_DESCRIPTION_LEN;
pub const SKILL_MAX_DEFAULT_PROMPT_LEN: usize = SKILL_MAX_DESCRIPTION_LEN;
pub const SKILL_MAX_DEPENDENCY_TYPE_LEN: usize = SKILL_MAX_NAME_LEN;
pub const SKILL_MAX_DEPENDENCY_TRANSPORT_LEN: usize = SKILL_MAX_NAME_LEN;
pub const SKILL_MAX_DEPENDENCY_VALUE_LEN: usize = SKILL_MAX_DESCRIPTION_LEN;
pub const SKILL_MAX_DEPENDENCY_DESCRIPTION_LEN: usize = SKILL_MAX_DESCRIPTION_LEN;
pub const SKILL_MAX_DEPENDENCY_COMMAND_LEN: usize = SKILL_MAX_DESCRIPTION_LEN;
pub const SKILL_MAX_DEPENDENCY_URL_LEN: usize = SKILL_MAX_DESCRIPTION_LEN;
pub const SKILL_MAX_SCAN_DEPTH: usize = 6;
pub const SKILL_MAX_DIRS_PER_ROOT: usize = 2_000;

pub const SESSION_MEMORY_RENDERED_CHARS: usize = 10_000;
pub const SESSION_MEMORY_COMPACT_RENDERED_CHARS: usize = 7_000;
pub const SESSION_MEMORY_TIGHT_RENDERED_CHARS: usize = 6_000;
pub const SESSION_MEMORY_CRITICAL_RENDERED_CHARS: usize = 3_500;
pub const SESSION_MEMORY_CACHE_HIT_MESSAGE_CHARS: usize = 520;
pub const SESSION_MEMORY_ACCESS_LOG_ENTRIES: usize = 40;
pub const SESSION_MEMORY_CHANGED_PATHS: usize = 48;
pub const SESSION_MEMORY_VERIFICATIONS: usize = 16;
pub const SESSION_MEMORY_RECENT_ITEMS: usize = 20;
pub const SESSION_MEMORY_LEDGER_ENTRIES: usize = 16;
pub const SESSION_MEMORY_DECISIONS: usize = 20;
pub const SESSION_MEMORY_REUSE_HINTS: usize = 16;
pub const SESSION_MEMORY_REASONING_CACHE_ENTRIES: usize = 16;
pub const SESSION_MEMORY_OPERATION_CACHE_ENTRIES: usize = 48;
pub const SESSION_MEMORY_RENDERED_REASONING_CACHE_ENTRIES: usize = 2;
pub const SESSION_MEMORY_CACHED_FILE_BYTES: u64 = 2 * 1024 * 1024;
pub const SESSION_MEMORY_TASK_INTENT_LINES: usize = 6;
pub const SESSION_MEMORY_TASK_INTENT_CHARS: usize = 1_500;
pub const SESSION_MEMORY_OPEN_QUESTIONS: usize = 5;
pub const SESSION_MEMORY_LATEST_TURN_DELTA: usize = 16;

pub const HISTORY_CONTINUITY_TEXT_BYTES: usize = 4_096;
pub const HISTORY_CONTINUITY_PREVIOUS_TURN_MODEL_BYTES: usize = 160;

pub const WORKING_CONTEXT_BRIEF_CHARS: usize = 3_500;
pub const WORKING_CONTEXT_BRIEF_DIAGNOSTIC_LINES: usize = 18;
pub const WORKING_CONTEXT_BRIEF_FAILURES: usize = 4;
pub const WORKING_CONTEXT_BRIEF_TEXT_PREVIEW_CHARS: usize = 240;

pub const TOOL_FAILURE_RECOVERY_DEFAULT_FAILURE_THRESHOLD: usize = 2;
pub const TOOL_FAILURE_RECOVERY_FAILURE_REARM_INTERVAL: usize = 3;
pub const TOOL_FAILURE_RECOVERY_NO_PROGRESS_THRESHOLD: usize = 2;
pub const TOOL_FAILURE_RECOVERY_NO_PROGRESS_REARM_INTERVAL: usize = 3;
pub const TOOL_FAILURE_RECOVERY_FAILURES_IN_HINT: usize = 4;
pub const TOOL_FAILURE_RECOVERY_FAILURE_TEXT_CHARS: usize = 240;
pub const TOOL_FAILURE_RECOVERY_PROGRESS_TEXT_CHARS: usize = 240;

pub const GIT_CONTEXT_DIRTY_PATH_CAP: usize = 60;
pub const GIT_CONTEXT_FRAGMENT_LINES: usize = 60;

pub const ADDITIONAL_CONTEXT_CHANGED_ENTRIES: usize = 8;
pub const ADDITIONAL_CONTEXT_CHANGED_BYTES: usize = 8 * 1024;

pub const SOURCE_EVIDENCE_ITEMS: usize = 64;
pub const SOURCE_AUDIT_ITEMS: usize = 64;
pub const SOURCE_CITATIONS: usize = 96;

pub const MEMORY_MAX_ROLLOUTS_PER_STARTUP: usize = 2;
pub const MEMORY_MAX_ROLLOUT_AGE_DAYS: i64 = 10;
pub const MEMORY_MIN_ROLLOUT_IDLE_HOURS: i64 = 6;
pub const MEMORY_MIN_RATE_LIMIT_REMAINING_PERCENT: i64 = 25;
pub const MEMORY_MAX_RAW_MEMORIES_FOR_CONSOLIDATION: usize = 256;
pub const MEMORY_MAX_UNUSED_DAYS: i64 = 30;
pub const MEMORY_MIN_RAW_MEMORIES_FOR_CONSOLIDATION: usize = 1;
pub const MEMORY_HARD_MAX_RAW_MEMORIES_FOR_CONSOLIDATION: usize = 4_096;
pub const MEMORY_MIN_ROLLOUTS_PER_STARTUP: usize = 1;
pub const MEMORY_HARD_MAX_ROLLOUTS_PER_STARTUP: usize = 128;
pub const MEMORY_TOOL_DEFAULT_LIST_MAX_RESULTS: usize = 200;
pub const MEMORY_TOOL_MAX_LIST_RESULTS: usize = 2_000;
pub const MEMORY_TOOL_DEFAULT_SEARCH_MAX_RESULTS: usize = 25;
pub const MEMORY_TOOL_MAX_SEARCH_RESULTS: usize = 200;
pub const MEMORY_TOOL_DEFAULT_READ_MAX_TOKENS: usize = 8_000;
pub const MEMORY_CONTEXT_DEFAULT_MAX_ITEMS: usize = 20;
pub const MEMORY_CONTEXT_DEFAULT_MAX_TOKENS: usize = 2_500;
pub const MEMORY_CONTEXT_SHARE_PERCENT: usize = 22;
pub const MEMORY_CONTEXT_RENDER_OVERHEAD_TOKENS: usize = 96;

pub const UNIFIED_EXEC_DEFAULT_MAX_OUTPUT_TOKENS: usize = 18_000;
pub const UNIFIED_EXEC_MIN_YIELD_TIME_MS: u64 = 250;
pub const UNIFIED_EXEC_WINDOWS_INITIAL_YIELD_TIME_FLOOR_MS: u64 = 2_000;
pub const UNIFIED_EXEC_MIN_EMPTY_YIELD_TIME_MS: u64 = 5_000;
pub const UNIFIED_EXEC_MAX_YIELD_TIME_MS: u64 = 30_000;
pub const UNIFIED_EXEC_DEFAULT_BACKGROUND_TERMINAL_TIMEOUT_MS: u64 = 900_000;
pub const UNIFIED_EXEC_OUTPUT_MAX_BYTES: usize = 1024 * 1024;
pub const UNIFIED_EXEC_MAX_PROCESSES: usize = 64;
pub const UNIFIED_EXEC_OUTPUT_DELTA_MAX_BYTES: usize = 16_384;

pub const TOOL_SCHEMA_COMPACT_BYTES: usize = 6_000;
pub const TOOL_SCHEMA_COMPACT_DEPTH: usize = 3;
pub const TOOL_SEARCH_DEFAULT_LIMIT: usize = 12;
pub const TOOL_SEARCH_VISIBLE_RESULT_LIMIT: usize = 12;
pub const TOOL_SEARCH_HANDLER_CACHE_ENTRIES: usize = 4;
pub const TOOL_SEARCH_RESULT_CACHE_ENTRIES: usize = 32;
pub const TOOL_SEARCH_CANDIDATE_MULTIPLIER: usize = 3;
pub const TOOL_SLEEP_MAX_DURATION_MS: u64 = 3_600_000;
pub const AGENT_JOB_DEFAULT_CONCURRENCY: usize = 16;
pub const AGENT_JOB_MAX_CONCURRENCY: usize = 64;
pub const TOOL_TELEMETRY_PREVIEW_MAX_BYTES: usize = 2 * 1024;
pub const TOOL_TELEMETRY_PREVIEW_MAX_LINES: usize = 64;
pub const LIST_AVAILABLE_PLUGINS_DESCRIPTION_CHARS: usize = 240;
pub const MULTI_AGENT_MODEL_OVERRIDES_IN_DESCRIPTION: usize = 5;
pub const MULTI_AGENT_REASONING_EFFORT_CHARS_IN_DESCRIPTION: usize = 64;
pub const DIRECT_MCP_TOOL_EXPOSURE_THRESHOLD: usize = 100;
pub const MCP_RESULT_TELEMETRY_TARGET_ID_CHARS: usize = 256;
pub const MCP_TOOL_CALL_EVENT_RESULT_MAX_BYTES: usize = 1024 * 1024;
pub const MCP_NON_JSON_RESPONSE_BODY_PREVIEW_BYTES: usize = 8_192;
pub const MCP_TOOL_NAME_LENGTH: usize = 64;

pub const PLUGIN_CAPABILITY_SUMMARY_DESCRIPTION_LEN: usize = 1_024;
pub const PLUGIN_DEFAULT_PROMPT_COUNT: usize = 3;
pub const PLUGIN_DEFAULT_PROMPT_LEN: usize = 128;
pub const REMOTE_PLUGIN_LIST_PAGE_LIMIT: u32 = 200;
pub const REMOTE_PLUGIN_BUNDLE_MAX_DOWNLOAD_BYTES: u64 = 50 * 1024 * 1024;
pub const REMOTE_PLUGIN_BUNDLE_ERROR_BODY_MAX_BYTES: u64 = 8 * 1024;
pub const REMOTE_PLUGIN_BUNDLE_MAX_EXTRACTED_BYTES: u64 = 250 * 1024 * 1024;
pub const REMOTE_PLUGIN_SHARE_MAX_ARCHIVE_BYTES: usize = 50 * 1024 * 1024;

pub const CODE_MODE_NAMESPACE_DESCRIPTION_BYTES: usize = 1_200;
pub const CODE_MODE_NESTED_TOOL_DESCRIPTION_BYTES: usize = 2_400;
pub const CODE_MODE_NESTED_TOOL_REFERENCE_BYTES: usize = 32_000;

pub const HOOK_OUTPUT_TOKEN_LIMIT: usize = 2_500;
pub const WEB_SEARCH_ASSISTANT_CONTEXT_TOKEN_LIMIT: usize = 1_000;

pub const APP_SERVER_OUTPUT_BYTES_CAP: usize = 1024 * 1024;
pub const APP_SERVER_OUTPUT_CHUNK_SIZE_HINT: usize = 64 * 1024;
pub const APP_SERVER_PROCESS_CONTROL_CHANNEL_CAPACITY: usize = 32;
pub const REMOTE_CONTROL_RESPONSE_BODY_MAX_BYTES: usize = 4_096;
pub const REMOTE_CONTROL_SEGMENT_TARGET_BYTES: usize = 100 * 1024;
pub const REMOTE_CONTROL_SEGMENT_MAX_BYTES: usize = 150 * 1024;
pub const REMOTE_CONTROL_REASSEMBLED_MAX_BYTES: usize = 100 * 1024 * 1024;
pub const REMOTE_CONTROL_SEGMENT_COUNT_MAX: usize = 1024;
pub const REMOTE_CONTROL_SEGMENT_ASSEMBLY_MAX_COUNT: usize = 128;
pub const WEBSOCKET_OUTBOUND_CHANNEL_CAPACITY: usize = 32 * 1024;
pub const TUI_THREAD_EVENT_CHANNEL_CAPACITY: usize = 32 * 1024;
pub const DYNAMIC_TOOL_NAME_MAX_LEN: usize = 128;
pub const DYNAMIC_TOOL_NAMESPACE_MAX_LEN: usize = 64;
pub const DYNAMIC_TOOL_NAMESPACE_DESCRIPTION_MAX_LEN: usize = 1024;

pub const CONTEXT_WINDOW_BASELINE_TOKENS: i64 = 12_000;

pub const SHELL_OUTPUT_DEFAULT_SUMMARY_AFTER_BYTES: usize = 48 * 1024;
pub const SHELL_OUTPUT_DEFAULT_SUMMARY_AFTER_LINES: usize = 600;
pub const SHELL_OUTPUT_EARLY_SUMMARY_AFTER_BYTES: usize = 10 * 1024;
pub const SHELL_OUTPUT_EARLY_SUMMARY_AFTER_LINES: usize = 160;
pub const SHELL_OUTPUT_SUMMARY_MAX_BYTES: usize = 32 * 1024;
pub const SHELL_OUTPUT_SUMMARY_MAX_LINES: usize = 240;
pub const SHELL_OUTPUT_SUCCESS_HEAD_LINES: usize = 24;
pub const SHELL_OUTPUT_SUCCESS_TAIL_LINES: usize = 64;
pub const SHELL_OUTPUT_FAILURE_TAIL_LINES: usize = 140;
pub const SHELL_OUTPUT_FOCUS_CONTEXT_LINES: usize = 3;
pub const SHELL_OUTPUT_MAX_FOCUS_MATCHES: usize = 48;

pub const SOURCE_SEARCH_DEFAULT_MAX_MATCHES: usize = 100;
pub const SOURCE_SEARCH_MAX_MATCHES: usize = 500;
pub const SOURCE_SEARCH_CORE_DEFAULT_READ_LINES: usize = 40;
pub const SOURCE_SEARCH_CORE_MAX_READ_LINES: usize = 220;
pub const SOURCE_SEARCH_CORE_MAX_FILE_BYTES: usize = 256 * 1024;
pub const SOURCE_SEARCH_CONTEXT_LINES: usize = 5;
pub const SOURCE_SEARCH_CORE_MAX_FILES: usize = 5_000;
pub const SOURCE_SEARCH_CORE_MAX_BYTES: usize = 3 * 1024 * 1024;
pub const SOURCE_SEARCH_MAX_RANKED_CANDIDATES: usize = 10;
pub const SOURCE_SEARCH_MAX_QUERY_EXPANSION_TERMS: usize = 24;
pub const SOURCE_SEARCH_MAX_RELATED_SEARCHES: usize = 20;
pub const SOURCE_SEARCH_MAX_SUGGESTED_READS_PER_CANDIDATE: usize = 8;
pub const SOURCE_SEARCH_MAX_NEXT_READ_SEQUENCE: usize = 32;
pub const SOURCE_SEARCH_MAX_SURFACE_ENTRIES: usize = 200;
pub const SOURCE_SEARCH_MAX_SURFACE_LIST: usize = 150;
pub const SOURCE_SEARCH_CACHE_ENTRIES: usize = 128;
pub const SOURCE_SEARCH_SPAN_READ_RECORDS_PER_FILE: usize = 16;
pub const SOURCE_SEARCH_CLI_MAX_FILES: usize = 2_000;
pub const SOURCE_SEARCH_CLI_MAX_BYTES: usize = 16 * 1024 * 1024;
pub const SOURCE_SEARCH_CLI_MAX_FILE_BYTES: u64 = 2 * 1024 * 1024;
pub const SOURCE_SEARCH_CLI_MAX_READ_LINES: usize = 400;

pub const COMPACT_USER_MESSAGE_MAX_TOKENS: usize = 6_000;
pub const REMOTE_COMPACTION_RETAINED_MESSAGE_TOKEN_BUDGET: usize = 12_000;

pub const REALTIME_STARTUP_CONTEXT_TOKEN_BUDGET: usize = 8_000;
pub const REALTIME_ASSISTANT_OUTPUT_TOKEN_BUDGET: usize = 1_000;
pub const REALTIME_CURRENT_THREAD_SECTION_TOKEN_BUDGET: usize = 4_000;
pub const REALTIME_RECENT_WORK_SECTION_TOKEN_BUDGET: usize = 2_000;
pub const REALTIME_WORKSPACE_SECTION_TOKEN_BUDGET: usize = 1_000;
pub const REALTIME_NOTES_SECTION_TOKEN_BUDGET: usize = 200;
pub const REALTIME_TURN_TOKEN_BUDGET: usize = 300;
pub const REALTIME_RECENT_THREADS: usize = 40;
pub const REALTIME_RECENT_WORK_GROUPS: usize = 8;
pub const REALTIME_CURRENT_CWD_ASKS: usize = 8;
pub const REALTIME_OTHER_CWD_ASKS: usize = 5;
pub const REALTIME_ASK_CHARS: usize = 240;
pub const REALTIME_TREE_MAX_DEPTH: usize = 2;
pub const REALTIME_DIR_ENTRY_LIMIT: usize = 20;

pub const ADDITIONAL_CONTEXT_VALUE_TOKENS: usize = 1_000;
pub const SKILLS_EXTENSION_AVAILABLE_SKILLS_BYTES: usize = 8_000;
pub const SKILLS_EXTENSION_MAIN_PROMPT_BYTES: usize = 8_000;
pub const SKILLS_EXTENSION_SKILL_NAME_BYTES: usize = 256;
pub const SKILLS_EXTENSION_SKILL_PATH_BYTES: usize = 1_024;
pub const ORCHESTRATOR_SKILL_RESOURCE_PAGES: usize = 10;
pub const ORCHESTRATOR_SKILLS: usize = 100;
pub const ORCHESTRATOR_SKILL_NAME_BYTES: usize = 64;
pub const ORCHESTRATOR_SKILL_DESCRIPTION_BYTES: usize = 128;
pub const ORCHESTRATOR_SKILL_SOURCE_BYTES: usize = 1_024;
pub const ORCHESTRATOR_SKILL_TITLE_BYTES: usize = 2_048;
pub const ORCHESTRATOR_SKILL_RESOURCE_CONTENT_BYTES: usize = 1024 * 1024;
pub const ORCHESTRATOR_CACHED_RESOURCES: usize = 100;
pub const ORCHESTRATOR_CACHED_CONTENT_BYTES: usize = 8 * 1024 * 1024;

pub const EXTERNAL_AGENT_SESSION_TITLE_LEN: usize = 120;
pub const EXTERNAL_AGENT_NOTE_LEN: usize = 2_000;
pub const EXTERNAL_AGENT_TOOL_RESULT_LEN: usize = 4_000;
pub const IMAGE_GENERATION_OUTPUT_HINT_BYTES: usize = 1_024;
pub const IGNORE_LARGE_UNTRACKED_FILES_BYTES: i64 = 10 * 1024 * 1024;
pub const EXEC_OUTPUT_DELTAS_PER_CALL: usize = 10_000;
pub const EXEC_AGGREGATE_BUFFER_INITIAL_CAPACITY: usize = 8 * 1024;
pub const EXEC_DEFAULT_COMMAND_TIMEOUT_MS: u64 = 15 * 60 * 1000;
pub const EXEC_READ_CHUNK_SIZE: usize = 8_192;
pub const EXEC_IO_DRAIN_TIMEOUT_MS: u64 = 2_000;

pub const IMAGE_RESIZED_BYTES_ESTIMATE: i64 = 7_373;
pub const IMAGE_ORIGINAL_MAX_PATCHES: usize = 10_000;
pub const IMAGE_ORIGINAL_ESTIMATE_CACHE_SIZE: usize = 32;

pub const GUARDIAN_CONSECUTIVE_DENIALS_PER_TURN: u32 = 3;
pub const GUARDIAN_RECENT_AUTO_REVIEW_DENIALS_PER_TURN: u32 = 10;
pub const GUARDIAN_AUTO_REVIEW_DENIAL_WINDOW_SIZE: usize = 50;
pub const GUARDIAN_MESSAGE_TRANSCRIPT_TOKENS: usize = 1_000;
pub const GUARDIAN_TOOL_TRANSCRIPT_TOKENS: usize = 1_000;
pub const GUARDIAN_MESSAGE_ENTRY_TOKENS: usize = 250;
pub const GUARDIAN_TOOL_ENTRY_TOKENS: usize = 250;
pub const GUARDIAN_ACTION_STRING_TOKENS: usize = 1_000;
pub const GUARDIAN_RECENT_ENTRY_LIMIT: usize = 40;

pub const TOKEN_BUDGET_USAGE_THRESHOLDS: [i64; 4] = [20, 40, 60, 80];

pub const IDE_ACTIVE_SELECTION_CHARS: usize = 40_000;
pub const IDE_OPEN_TABS: usize = 100;
pub const IDE_OPEN_TABS_CHARS: usize = 20_000;
pub const IDE_IPC_FRAME_BYTES: usize = 256 * 1024 * 1024;
pub const TUI_TOOL_CALL_MAX_LINES: usize = 5;
pub const TUI_USER_SHELL_TOOL_CALL_MAX_LINES: usize = 50;
pub const TUI_INTERACTION_PREVIEW_CHARS: usize = 80;
pub const TUI_OSC52_MAX_RAW_BYTES: usize = 100_000;
pub const TUI_RAW_TOOL_OUTPUT_WIDTH: usize = 10_000;
pub const TUI_HIGHLIGHT_BYTES: usize = 512 * 1024;
pub const TUI_HIGHLIGHT_LINES: usize = 10_000;
pub const TUI_LARGE_PASTE_CHAR_THRESHOLD: usize = 1_000;
pub const TUI_STATUS_DETAILS_DEFAULT_MAX_LINES: usize = 3;
pub const TUI_AGENT_STATUS_PREVIEW_LINES: usize = 3;
pub const TUI_AGENT_STATUS_PREVIEW_ITEMS: usize = 6;
pub const TUI_AGENT_STATUS_PREVIEW_GRAPHEMES: usize = 240;
pub const TUI_COMMAND_LIFECYCLE_RECENT_CHUNKS: usize = 3;
pub const TUI_STREAMING_ENTER_QUEUE_DEPTH_LINES: usize = 8;
pub const TUI_STREAMING_EXIT_QUEUE_DEPTH_LINES: usize = 2;
pub const TUI_STREAMING_SEVERE_QUEUE_DEPTH_LINES: usize = 64;
pub const TUI_TERMINAL_RESIZE_REFLOW_FALLBACK_MAX_ROWS: u16 = 1_000;

pub const DOCTOR_PROBE_ERROR_CHARS: usize = 120;
pub const DOCTOR_PARITY_SCAN_FILES: usize = 10_000;
pub const DOCTOR_SAMPLE_LIMIT: usize = 5;
pub const DOCTOR_SUMMARY_LIMIT: usize = 8;
pub const DOCTOR_OUTPUT_LIST_LIMIT: usize = 7;
pub const DOCTOR_OUTPUT_PATH_LIMIT: usize = 48;
pub const CLI_PROJECT_TITLE_MAX_CHARS: usize = 24;
pub const FEEDBACK_DEFAULT_MAX_BYTES: usize = 4 * 1024 * 1024;
pub const FEEDBACK_MAX_TAGS: usize = 64;
pub const SKILL_LIST_MAX_WARNINGS: usize = 4;
pub const SKILL_LIST_MAX_WARNING_BYTES: usize = 256;
