begin_patch: "*** Begin Patch" LF
end_patch: "*** End Patch" LF?

hunk: add_hunk | delete_hunk | update_hunk
add_hunk: "*** Add File: " filename LF add_line*
delete_hunk: "*** Delete File: " filename LF
update_hunk: "*** Update File: " filename LF (change_move change? | change)

filename: /(.+)/
add_line: "+" /(.+)/? LF -> line

change_move: "*** Move to: " filename LF
change: (change_context | change_line)+ eof_line?
change_context: ("@@" | "@@ " /(.+)/) LF
change_line: ("+" | "-" | " ") /(.+)/? LF
eof_line: "*** End of File" LF

%import common.LF

retry: "*** Retry Patch: " patch_id LF amendment*
amendment: "*** Replace Hunk: " index LF hunk | "*** Replace Chunk: " index " " index LF change
patch_id: /[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/
index: /[1-9][0-9]*/
